var all = [
    ["March","三月"],
    ["July","七月"],
    ["aware", "知道/意识"],
    ["working hard to", "努力工作"],
    ["quarantine", "隔离"],
    ["solar eclipse", "日食"],
    ["forward with", "前进"],
    ["solar eclipses", "日食"],
    ["This month’s eclipse", "这个月的月蚀"],
    ["Capricorn-Cancer", "摩羯座"],
    ["every six months", "每6个月"],
    ["It all started back in", "这一切都始于"],
    ["Even so", "即便如此"],
    ["insurance", "保险"],
    ["create surprises for you", "为你创造惊喜"],
    ["Cancer-Capricorn", "巨蟹座-摩羯座"],
    ["and will end now", "现在就要结束了"],
    ["New moon eclipses", "新月食"],
    ["lunar eclipses", "月食"],
    ["eclipses", "(日食+月食)"],
    ["sunny", "阳光"],
    ["urgent", "紧急的"],
    ["limiting", "限制"],
    ["marks", "标志"],
    ["credit card", "信用卡"],
    ["commission check", "佣金"],
    ["movements", "运动/行动"],
    ["grip", "影响力"],
    ["shoulders", "肩膀"],
    ["premium—something", "高级的东西"],
    ["axis", "轴"],
    ["owes you money", "欠你钱"],
    ["significant", "显著的/有重大意义的"],
    ["Sagittarius-Gemini", "射手座-双子座"],
    ["June", "六月"],
    ["full moon lunar eclipse", "满月月食"],
    ["Gemini", "双子座"],
    ["penalties", "处罚"],
    ["In short", "简而言之"],
    ["charge", "指控"],
    ["work out well", "进展顺利"],
    ["Sagittarius", "射手座"],
    ["Saturn", "土星"],
    ["greatest","最大的"],
    ["determination", "决心(n)"],
    ["Pluto", "冥王星"],
    ["Capricorns", "摩羯座们"],
    ["Capricorn", "摩羯座"],
    ["spiritual", "精神的"],
    ["routine", "常规"],
    ["a host of", "一堆的"],
    ["so far", "目前为止"],
    ["challenging aspect", "挑战"],
    ["suddenly","突然(adv)"],
    ["Cancer", "巨蟹座"],
    ["astrology", "占星术"],
    ["super-strong", "超强"],
    ["a little differently", "一点点不同"],
    ["full and new moons", "满月和新月"],
    ["circumstances", "情况"],
    ["January", "一月"],
    ["December", "十二月"],
    ["listed", "被列出"],
    ["likely", "可能"],
    ["have felt", "已经 感受到"],
    ["recently", "最近的"],
    ["recent", "最近的"],
    ["redesign", "重新设计"],
    ["signs", "星座"],
    ["sign", "星座"],
    ["equanimity", "冷静"],
    ["New York City", "纽约"],
    ["for a short while", "很短的一段时间"],
    ["Aquarius", "水瓶座"],
    ["Have a look at", "看一看"],
    ["come through", "安然渡过"],
    ["universe", "宇宙"],
    ["dramatic", "戏剧性的"],
    ["rapid", "瞬间的"],
    ["out of left field", "超出常理"],
    ["eclipse", "日食/月食"],
    ["emotional", "感情影响力的"],
    ["highly", "很有"],
    ["revolution", "变革"],
    ["equality", "平等(n)"],
    ["death", "死亡"],
    ["George Floyd", "乔治·弗洛伊德"],
    ["horrendous", "可怕的"],
    ["dealing with", "处理/处理"],
    ["vigorous lessons", "有力的教训"],
    ["by the door", "在门边"],
    ["quality", "素质/品质"],
    ["deliver", "发布"], 
    ["partnerships", "伙伴关系"],
    ["reward—material", "奖励材料"],
    ["realize", "实现"],
    ["Keep in mind", "记住"],
    ["refresher", "复习"],
    ["course", "课程"],
    ["brave", "勇敢的"],
    ["worry about", "担忧"],
    ["accomplished", "完成了"],
    ["justice", "公正"],
    ["floodlight", "泛光灯"],
    ["clue", "线索"],
    ["unexpected", "出乎意料的"],
    ["insight", "了解/领悟(n)"],
    ["certainly", "毫无疑问的(adv)"],
    ["fault", "过错"],
    ["particularly", "尤其(adv)"],
    ["In other words", "换句话说"],
    ["accurately", "准确的(adv)"],
    ["probably", "很可能"],
    ["pressure", "压力"],
    ["culmination", "顶点/高潮"],
    ["deal with", "处理"],
    ["puzzle", "令人疑惑的/费解的"],
    ["eureka", "[eureka](因找到某物，尤指问题的答案而高兴)我发现了，我找到了"],
    ["sentimental", "感情的"],
    ["entire", "全部的"],
    ["distracted", "注意力不集中"],
    ["step up", "加快/增加"],
    ["stress", "心理压力"],
    ["constant", "连续发生的/重复的(adj)"],
    ["Alas", "唉"],
    ["refresh","使恢复/涣新" ],
    ["fresh", "新的/不同的"],
    ["opportunities", "机会"],
    ["turbulent", "动荡的(adj)"],
    ["emphasis", "强调"],
    ["lately", "最近(adv)"],
    ["announcement", "公告/通知"],
    ["August", "八月"],
    ["Mercury", "水星"],
    ["strategic", "战略性的"],
    ["quiet", "平静的"],
    ["tone", "语气"],
    ["realistic", "现实的"],
    ["natal", "出生时的"],
    ["defeat", "失败/战败"],
    ["phoenix", "凤凰"],
    ["adjustments", "调整"],
    ["outcome", "结果"],
    ["Meanwhile", "同时"],
    ["Mars", "火星"],
    ["capture", "捕获/夺得"], 
    ["apartment", "公寓"], 
    ["continuously", "连续不断地(adv)"],
    ["September", "九月"],
    ["weigh", "权衡"],
    ["November", "十一月"],
    ["meditating", "冥想/考虑"],
    ["exerting", "施加"],
    ["challenge", "挑战"],
    ["path", "道路"],
    ["seeking", "寻求"],
    ["retrograde", "倒退/逆行"],
    ["trend", "趋势"],
    ["younger", "更年轻"],
    ["key role", "关键角色"],
    ["possibly","可能"],
    ["past", "过去的"],
    ["Planets", "行星"],
    ["adjust", "调整"],
    ["Additionally", "另外"],
    ["planet", "行星"],
    ["devastating", "毁灭性的"],
    ["responsibilities", "责任(n)"],
    ["outermost", "最外层"],
    ["track", "轨道"],
    ["ashes", "灰烬"],
    ["slightest", "最轻微的"],
    ["response", "响应/回答"],
    ["opposite", "相反的"],
    ["complaints", "投诉"],
    ["expect", "期待"],
    ["assumptions", "假设"],
    ["singled out", "挑选出"],
    ["sync", "同步"],
    ["Neptune", "海王星"],
    ["foundation", "基础"],
    ["sturdy", "坚固/强壮的"],
    ["straight", "直的"],
    ["experience", "遭受/体验"],
    ["taught", "教"],
    ["severe", "严厉的/苛刻的"],
    ["self-pity", "自怜"],
    ["yet", "然而"],
    ["heard", "听到过"],
    ["practical", "实际的"],
    ["Concentrate", "集中注意力"],
    ["sorrow", "悲伤"],
    ["population", "人口"],
    ["ambitious", "雄心勃勃的"],
    ["cope", "处理"],
    ["aspect","方面"],
    ["fortifying", "强化"],
    ["boosting", "助推"],
    ["boost", "促进"],
    ["woodland", "树林/林地"],
    ["steal", "偷"],
    ["charms", "魅力"],
    ["strength", "力量"],
    ["rebound", "反弹/振作"],
    ["illustrated", "说明/显示"],
    ["prominent", "显著的"],
    ["hop in your car and go", "上车去并走"],
    ["chart", "星盘图"],
    ["transiting", "行运"],
    ["absolutely", "绝对的"],
    ["interested in", "关注"],
    ["regarding", "认为是"],
    ["partnership", "合作关系"],
    ["speed up", "加快"],
    ["happening out", "发生"],
    ["touching", "接触"],
    ["decision","决策"],
    ["partner", "搭档"],
    ["anyway", "无论如何"],
    ["trace", "追溯/追踪"],
    ["outside", "外部"],
    ["directly", "直接地"],
    ["in this direction", "朝这个方向"],
    ["direct", "直接的"],
    ["effect", "影响"],
    ["consciously", "有意识地"],
    ["aware of", "意识到"],
    ["although", "即使"],
    ["occurs", "发生"],
    ["new moon", "新月"],
    ["normal", "寻常的"],
    ["nevertheless", "不过(提到前面)"],
    ["spouse", "配偶"],
    ["tension", "紧张"],
    ["comes up", "即将发生"],
    ["discussion", "讨论"],
    ["established", "已经确定关系的"],
    ["steady date", "稳定的约会"],
    ["a great deal of", "许多的"],
    ["appears", "显示"],
    ["will be", "将会(是/被)"],
    ["on the same page", "意见一致(在同一立场上)"],
    ["matter", "事件/当前的状况"],
    ["surfaces", "表面(n)/水面"],
    ["fix-up", "修正"],
    ["residential", "住宅的"],
    ["enact", "进行"],
    ["hammering", "击碎/锤击"],
    ["elderly", "年纪较大的"],
    ["fix", "固定"],
    ["struggle", "斗争"],
    ["rug", "垫子"],
    ["fatigue", "乏力/劳累"],
    ["get carried away", "忘乎所以/急不可待"],
    ["be related to ", "与...有关"],
    ["in regard to", "关于"],
    ["occur", "发生/出现"],
    ["timeline", "时间轴"],
    ["give into", "屈服于"],
    ["acceptable", "可接受的"],
    ["separation", "隔离/分离"],
    ["vaccine", "疫苗"],
    ["decorator", "装饰工"],
    ["blown rise", "吹起上升"],
    ["architect", "建筑师/设计师"],
    ["roommate", "室友"],
    ["landlord", "房东"],
    ["usually", "通常"],
    ["topic", "话题"],
    ["arise", "出现"],
    ["hinge", "铰链"],
    ["arguments", "争吵"],
    ["swept", "打扫"],
    ["motivation", "动机"],
    ["workmen", "工匠"],
    ["joint property", "共有财产"],
    ["amount", "数量"],
    ["cleanse difficulties", "清除困难"],
    ["major","重要的"],
    ["division", "拆分/分开"],
    ["debate", "讨论"],
    ["indicating", "显示/表明"],
    ["tempted to", "希望"],
    ["at all costs", "不惜任何代价"],
    ["anxious", "渴望/焦虑"],
    ["oppose", "反对/不支持/站在对面"],
    ["battle","战斗"],
    ["Jupiter", "木星"],
    ["living quarter", "居住区"],
    ["harmony", "和谐"],
    ["feature", "特征"],
    ["February", "二月"],
    ["sextile","六分相"],
    ["apart", "相距"],
    ["tiny", "微小的"],
    ["forging opportunity", "创造机会"],
    ["misinformation", "形成"],
    ["form", "形成"],
    ["delayed mails", "延误的邮件"],
    ["shipments", "运输/运送"],
    ["confusion", "混乱"],
    ["going on", "继续"],
    ["crystalize", "具体化"],
    ["electronics", "电子器械"],
    ["obstacles", "障碍物/绊脚石"],
    ["weak", "虚弱"],
    ["take the lead", "帅先/带头"],
    ["enormous", "巨大的"],
    ["cousin", "堂兄(妹)"],
    ["perhaps", "可能"],
    ["situation", "情况"],
    ["no doubt", "毫无疑问"],
    ["clearly", "清楚的"],
    ["concerns", "影响"],
    ["interactions", "相互影响"],
    ["on the sidelines", "在一旁"],
    ["eighth house", "第八宫"],
    ["appear to", "似乎"],
    ["rampage", "横冲直撞"],
    ["dominant", "占优势/首要的"],
    ["awards", "奖品/奖状"],
    ["move forward", "向前进"],
    ["war", "战争(war)"],
    ["turns", "转身/翻动"],
    ["angry", "生气的"],
    ["storming the gate", "冲进大门"],
    ["crowd of ","一群"],
    ["twists", "扭曲变形"],
    ["advancement", "进步"],
    ["Venus", "金星"],
    ["diplomacy", "外交手腕"],
    ["especially", "尤其是"],
    ["damage", "损害"],
    ["exception", "一般情况以外/例外"],
    ["be willing to", "愿意"],
    ["taunt ", "嘲弄/奚落"],
    ["this point", "这一点"],
    ["dynamite", "炸药"],
    ["fits", "突发情况"],
    ["keep at it", "坚持下去"],
    ["be granted", "被给予"],
    ["accountant", "会计"],
    ["lawyer", "律师"],
    ["general pandemonium", "大混乱"],
    ["sweetheart", "恋人"],
    ["steady", "稳定的"],
    ["committed", "承诺的"],
    ["quite", "相当的(adv)"],
    ["be helpful to", "有助于"],
    ["mentioned","提到"],
    ["almost", "几乎"],
    ["all along", "一直"],
    ["energy", "能量"],
    ["sticky", "黏(性)的"],
    ["stick", "火柴"],
    ["instead", "相反"],
    ["Instantly", "立即/马上"],
    ["wound", "使受伤"],
    ["all kinds of", "各种各样的"],
    ["inspiration", "灵感"],
    ["field", "领域"],
    ["convince", "说服"],
    ["creative", "创造性的"],
    ["contractor","承包商"],
    ["fuel", "燃料"],
    ["interfering with", "干扰"],
    ["conflict with", "与...冲突"],
    ["actor", "演员"],
    ["consider", "考虑"],
    ["unsupportive", "不支持"],
    ["merits", "优点"],
    ["brilliant", "明亮的/使人印象深的"],
    ["novels", "小说"],
    ["unstable", "不稳定"],
    ["cover an expense", "支付费用"],
    ["expense", "费用"],
    ["put off", "推迟的"],
    ["grumpy", "暴躁"],
    ["unpredictability", "不可预测性的"],
    ["hit a home run", "打出本垒打"],
    ["feel", "感觉"],
    ["ventures", "风险投资"],
    ["require you", "要求你"],
    ["flawed", "有缺陷的"],
    ["simply", "简单的"],
    ["initiate", "启动"],
    ["fee", "费用"],
    ["in the process of", "在...的过程中"],
    ["getting a divorce", "离婚"],
    ["generous","大量的"],
    ["apt", "倾向"],
    ["third", "第三"],
    ["concentration", "注意力"],
    ["communication","交流"],
    ["gorgeous", "美丽动人的"],
    ["April", "四月"],
    ["rendering", "导致"],
    ["orbit", "轨道"],
    ["no longer", "不再/再也不"],
    ["October", "10月"],
    ["digital", "数字的"],
    ["starts", "开始"],
    ["parts", "部分"],
    ["arts", "艺术"],
    ["diminish", "减少"],
    ["influential", "有很大影响的"],
    ["expressions", "表达"],
    ["positively", "绝对的"],
    ["screenplays", "电影剧本"],
    ["a bit", "一点"],
    ["cooperation", "合作"],
    ["forestfires", "森林火灾"],
    ["insurance company", "保险公司"],
    ["blocking", "阻塞"],
    ["opposing", "对立/反抗"],
    ["rest", "休息"],
    ["negotiate", "谈判"],
    ["In addition to", "除了"],
    ["minus", "减"],
    ["circulating","循环"],
    ["Scorpio", "天蝎座"],
    ["Pisces", "双鱼座"],
    ["Taurus", "金牛座"],
    ["Virgo","处女座"],
    ["hold off", "暂缓/推迟"],
    ["plus", "加"],
    ["breakup", "分手"],
    ["in a new light", "以新的视角"],
    ["appearance","外型"],
    ["reflect", "反映"],
    ["engagement", "订婚"],
    ["thrilling confession of love", "激动人心的爱情告白"],
    ["supportive", "给予帮助的"],
    ["enlightenment","启发"],
    ["bored with","厌倦"],
    ["extreme", "极端的"],
    ["tearful", "含泪的"],
    ["exceptionally", "破例"],
    ["fourth", "第四"],
    ["home", "家"],
    ["family", "家庭"],
    ["sector", "区域"],
    ["rather than", "而不是"],
    ["emphasize", "强调"],
    ["hard", "困难的"],
    ["square", "正方形/四分"],
    ["full moon", "满月"],
    ["noise", "噪音"],
    ["moving", "改变/移动"],
    ["massive","巨大的"],
    ["repair", "修理"],
    ["property", "财产"],
    ["renovation", "翻新"],
    ["parent", "父母"],
    ["different","不同(differ+ent)"],
    ["rent", "租金"],
    ["renovation", "翻新"],
    ["décor", "装饰"],
    ["guest", "客人"],
    ["Another way", "另一种方式"],
    ["timetable","时间安排表"],
    ["disagreement", "不同意"],
    ["agreement", "协议"],
    ["possessions", "财产"],
    ["custody", "拘留"],
    ["surprisingly", "出乎意料地"],
    ["splitting up", "分开/分手"],
    ["has nothing to do with you", "与你无关"],
    ["grace", "体面的/优雅"],
    ["fortitude","勇气/坚韧不拔"],
    ["inspire", "激励"],
    ["fair", "公平的"],
    ["productive", "有益的"],
    ["deeply", "深深地"],
    ["guarantee", "保证"],
    ["mathematical", "数字的"],
    ["Sometimes", "有时"],
    ["opposition to","对立/二分"],
    ["Aries","白羊座"],
    ["launch", "开始从事/发动/上市/发射"],
    ["working on", "致力于"],
    ["fact","事实"],
    ["entrepreneurial", "创业的"],
    ["outgo", "外出"],
    ["forging", "艰苦干成"],
    ["Alternatively", "或者"], 
    ["possibility", "机会/可能"],
    ["usual", "通常的"],
    ["expenses", "费用"],
    ["undergoing", "正在经历"],
    ["lifestyle", "生活/工作方式"],
    ["In that regard", "在这方面"],
    ["college", "大学"],
    ["graduate school","研究生院"],
    ["period", "时期"],
    ["spent","花费"],
    ["motivated", "激励"],
    ["income", "收入"],
    ["come up with", "想出"],
    ["strategies", "策略"],
    ["techniques", "技术"],
    ["cash flow", "现金流"],
    ["improvement", "改善n"],
    ["improve", "改善v"],
    ["left over", "剩下/留下"],
    ["spend", "花费"],
    ["is due on", "到期日"],
    ["create change", "创造改变"],
    ["tenth", "第十"],
    ["profession","职业"],
    ["suffering", "苦难/折磨"],
    ["solar", "太阳"],
    ["lunar","月亮"],
    ["filled with", "充满"],
    ["rally your relatives", "召集你的亲戚"],
    ["chip in", "共同凑钱"],
    ["victimized", "受害"],
    ["natural disasters", "自然灾害"],
    ["coronavirus", "冠状病毒"],
    ["virus", "病毒"],
    ["pregnant", "怀孕的"],
    ["good-fortune", "好运"],
    ["nature", "大自然"],
    ["plenty of", "很多"],
    ["divinely", "极好地"],
    ["whatever", "任何事情"],
    ["compatible", "兼容的"],
    ["fifth", "第五"],
    ["truelove", "真爱"],
    ["kick off", "开始"],
    ["ruler", "统治者"],
    ["enviable place", "令人羡慕的地方"],
    ["assertive", "坚定自信的"],
    ["latter", "后者"],
    ["introduction", "介绍"],
    ["far below", "远低于"],
    ["Experiencing", "经历"],
    ["bumble along with", "胡扯"],
    ["stage", "阶段"],
    ["surprising", "令人惊讶的"],
    ["rising", "上升"],
    ["Distribution","分配"],
    ["unplanned", "计划外的"],
    ["using my time alone", "独自一人"],
    ["qualities", "品质"],
    ["came her way", "来临/到达"],
    ["reach for", "伸手获得"],
    ["spins on", "旋转"],
    ["trouble", "使忧虑/痛苦"],
    ["jarring", "刺耳的/不和谐的"],
    ["medicine", "医学/药"],
    ["romance", "浪漫"],
    ["out of the blue", "出乎意料的"],
    ["relentless", "无情的/苛刻的"],
    ["cover an expense", "支付费用"],
    ["conversation", "交谈/谈话"],
    ["conjunct", "结合"],
    ["longest", "最长的"],
    ["indicate", "暗示"],
    ["chaos", "混乱"],
    ["surprise developments", "意外发展"],
    ["exhausted", "筋疲力尽的"],
    ["everyone", "每个人"],
    ["edgy", "烦躁不安的"],
    ["never", "从来没有"],
    ["offhand way", "随意的方式"],
    ["comment", "评论/解释/指责"],
    ["accidental", "意外的/偶然的"],
    ["harsh", "严酷的"],
    ["ever", "曾经"],
    ["snap", "不耐烦/斥责/大发雷霆"],
    ["be frustrated with", "对...感到沮丧"],
    ["necessary breaks", "必要的休息"],
    ["tougher", "严厉的/严峻的"],
    ["mettle", "勇气/毅力"],
    ["close to", "靠近/接近"],
    ["career", "事业"],
    ["overwhelming", "势不可挡的"],
    ["get ahead", "超前/获得成功"],
    ["willing to do", "甘愿做"],
    ["slowing down", "减速"],
    ["pace", "步伐"],
    ["mature", "甘愿"],
    ["intensify", "强化"],
    ["By the time", "到…的时候"],
    ["excitedly", "兴奋地"],
    ["divine", "天赐的"],
    ["holdover","延期"],
    ["slowdown", "减速"],
    ["ramp up", "增强/上升"],
    ["responsibility", "责任"],
    ["demands", "需求"],
    ["demanded", "要求"],
    ["piece", "块/片"],
    ["Philosopher", "思想家"],
    ["Plato", "柏拉图"],
    ["individual", "个人"],
    ["shine", "闪耀"],
    ["rare", "罕见的"],
    ["challenging", "具有挑战性的"],
    ["stern", "严厉的"],
    ["ruling", "统治的"],
    ["through", "穿透/通过"],
    ["paces", "步速"],
    ["toughened", "坚固/加强"],
    ["Libra", "天秤座"],
    ["breather", "短暂的休息"],
    ["presence", "存在/出现"],
    ["squabble", "争吵"],
    ["erupt", "爆发"],
    ["manifests", "表明"],
    ["argue", "争吵"],
    ["In that respect", "在这方面"],
    ["respect", "尊重"],
    ["sacrifice", "牺牲"],
    ["last", "上一个"],
    ["reaches","达到"],
    ["decisive", "果断的"],
    ["unconscious", "无意识的"],
    ["corresponding", "相应的"],
    ["reaction", "反应"],
    ["being treated", "被对待"],
    ["respond","回应"],
    ["mess", "混乱"],
    ["indicative", "显示/暗示"],
    ["Aside from", "除...之外"],
    ["profile", "轮廓"],
    ["honors", "名誉"],
    ["qualify", "有资格/使合格"],
    ["furniture", "家具"],
    ["better", "更好"],
    ["prime", "主要的/首要的"],
    ["between", "之间"],
    ["male", "男性的"],
    ["authority", "权威"],
    ["figure", "象征/符号"],
    ["bet", "打赌/估计"],
    ["a drive into the country", "开车取乡下"],
    ["haircut", "发型"],
    ["heading into", "进入"],
    ["so forth", "等等"],
    ["at the core of the reason", "原因的核心"],
    ["untoward", "不祥的"],
    ["achievement", "成就"],
    ["spread of", "传播"],
    ["flare up", "爆发"],
    ["perk up your morale", "振奋你的士气"],
    ["your hands full with", "手上满是"],
    ["oriented plans", "定向计划"],
    ["concerning", "关于/影响"],
    ["eleventh house", "第十一宫"],
    ["sum", "金额/款项"],
    ["make an appeal", "提出上诉"],
    ['arguing', '争辩'],
    ["much longer", "更久/长的多"],
    ["heated", "愤怒的"],
    ['wild', '放荡的/无人管教的'],
    ["I do hope this is not how things work out for you", "我真希望这不是你想要的"],
    ["physical", "身体的/物理的"],
    ["tied into", "卷入"],
    ["invite", "邀请/请求"],
    ["care for", "照顾"],
    ["romantic", "爱情的/浪漫的"],
    ["contention", "争论/争执"],
    ["forceful", "强有力的"],
    ["Still", "不过"],
    ["bright", "明亮的/闪亮的"],
    ["Uranus", "天王星"],
    ["beam", "光线/束"],
    ["possible", "可能的/可能存在(adj)"],
    ["involving", "牵涉"],
    ["ease", "轻易"],
    ["fight", "战斗"],
    ["favoring", "喜爱"],
    ["agent", "代理人"],
    ["fictional", "虚构的(小说的)"],
    ["imaginative", "富有想象力"],
    ["favoring", "偏爱"],
    ["pledge", "誓言"],
    ["spectrum", "光谱"],
    ["progress", "进展"],
    ["stagnated", "停滞不前"],
    ["proceed", "继续"],
    ["slowly", "缓慢地"],
    ["gradually", "逐步的"],
    ["haltingly", "犹豫地"],
    ["wise", "明智的"],
    ["clarify", "澄清"],
    ["particular", "特别"],
    ["fully", "完全的"],
    ["predestined", "命中注定的"],
    ["break up", "分手/结束关系"],
    ["spectrum", "光谱"],
    ["final", "最终的"],
    ["engaged", "订婚的"],
    ["decades", "几十年"],
    ["tough","艰难的"],
    ["retain", "保持"],
    ["stand out for", "显眼"],
    ["conjunction","连接"],
    ["expansive", "扩张的/友善的"],
    ["financial", "有钱的/财务的"],
    ["bubbling", "冒泡"],
    ["contact", "联络/接触"],
    ["translates into", "转化为"],
    ["profit from", "从...中获益/获利于"],
    ["put aside", "搁置/把…放在一边"],
    ["some time ago", "不久前"],
    ["reignite", "再次点燃/重燃"],
    ["ideal", "完美的"],
    ["far flung", "遥远的"],
    ["long to", "渴望"],
    ["shame", "羞愧"],
    ["gaze at one another", "互相凝视"],
    ["across the sky", "穿过天空"],
    ["gaze at", "凝视"],
    ["lyrical", "抒情的"],
    ["advantage", "优势"],
    ["spin off", "剥离出"],
    ["separate", "不同的/独立的"],
    ["directions", "方向"],
    ["perfume", "香味/芬香"],
    ["funds", "基金/资金"],
    ["extraordinary", "意想不到的"],
    ["calendar", "日历"],
    ["marriage", "结婚"],
    ["apologize", "道歉"],
    ["artistic", "艺术的"],
    ["readied", "准备就绪"],
    ["demand", "需要"],
    ["instant", "瞬间的/立即的"],
    ["opportunity", "机会"],
    ["heating up", "升温"],
    ["announce", "宣布"],
    ["At the time", "在那时"],
    ["rickety", "不结实的"],
    ["contrast", "功能"],
    ["Admittedly", "应当承认/不可否认"],
    ["odds", "可能性"],
    ["Leo", "狮子座"],
    ["arrive out of the blue", "突如其来/出乎意料地"],
    ["pregnancy", "怀孕"],
    ["infusion", "注入"],
    ["cash", "现金/资金"],
    ["unanticipated", "未预料到的"],
    ["resourceful", "足智多谋的/机敏的"],
    ["talent", "才能"],
    ["precipitated by you", "被你促成的"],
    ["climax", "高潮/顶点"],
    ["linger", "流连/持续"],
    ["mortgage", "抵押贷款"],
    ["loan", "贷款"],
    ["stimulus", "刺激"],
    ["rating", "评级"],
    ["Credit cards", "信用卡"],
    ["tax reductions", "减税"],
    ["accomplish", "完成"],
    ["average", "正常的/普通的"],
    ["inheritance", "继承"],
    ["refunds", "退款"],
    ["Mountain Goat", "山羊"],
    ["symbolizes", "象征"],
    ["ascend to", "上升到"],
    ["peaks", "高峰"],
    ["depths of the sea", "深海"],
    ["narrows", "变窄"],
    ["approach", "靠近"],
    ["pinnacle", "顶峰"],
    ["pass", "通过"],
    ["turtles", "海龟"],
    ["given up", "（given up）放弃"],
    ["legs", "腿"],
    ["on the climb", "在攀登"],
    ["surefootedness", "踏实"],
    ["reporter", "记者"],
    ["disappoint", "令人失望"],
    ["extent", "范围"],
    ["society", "社会"],
    ["residence", "住所"],
    ["pandemic", "大行流行病"],
    ["depending on", "取决于"],
    ["time zone", "时区"],
    ["settled down", "安定下来"],
    ["take place", "发生"],
    ["complications", "难题"]
];