var all = [
    ["March","三月"],
    ["July","七月"],
    ["quarantine", "隔离"],
    ["solar eclipse", "日食"],
    ["solar eclipses", "日食"],
    ["This month’s eclipse", "这个月的月蚀"],
    ["Capricorn-Cancer", "摩羯座"],
    ["every six months", "每6个月"],
    ["It all started back in", "这一切都始于"],
    ["Even so", "即便如此"],
    ["create surprises for you", "为你创造惊喜"],
    ["Cancer-Capricorn", "巨蟹座-摩羯座"],
    ["and will end now", "现在就要结束了"],
    ["New moon eclipses", "新月食"],
    ["eclipses", "(日食+月食)"],
    ["marks", "标志"],
    ["axis", "轴"],
    ["Sagittarius-Gemini", "射手座-双子座"],
    ["June", "六月"],
    ["full moon lunar eclipse", "满月月食"],
    ["Gemini", "双子座"],
    ["Sagittarius", "射手座"],
    ["Saturn", "土星"],
    ["greatest","最大的"],
    ["determination", "决心(n)"],
    ["Pluto", "冥王星"],
    ["Capricorns", "摩羯座们"],
    ["Capricorn", "摩羯座"],
    ["spiritual", "精神的"],
    ["a host of", "一堆的"],
    ["challenging aspect", "挑战"],
    ["suddenly","突然(adv)"],
    ["Cancer", "巨蟹座"],
    ["astrology", "占星术"],
    ["super-strong", "超强"],
    ["a little differently", "一点点不同"],
    ["full and new moons", "满月和新月"],
    ["circumstances", "情况"],
    ["January", "一月"],
    ["December", "十二月"],
    ["listed", "被列出"],
    ["likely", "可能"],
    ["have felt", "已经 感受到"],
    ["recently", "最近的"],
    ["recent", "最近的"],
    ["signs", "星座"],
    ["equanimity", "冷静"],
    ["New York City", "纽约"],
    ["for a short while", "很短的一段时间"],
    ["Aquarius", "水瓶座"],
    ["Have a look at", "看一看"],
    ["come through", "安然渡过"],
    ["universe", "宇宙"],
    ["dramatic", "戏剧性的"],
    ["rapid", "瞬间的"],
    ["out of left field", "超出常理"],
    ["eclipse", "日食/月食"],
    ["emotional", "感情影响力的"],
    ["highly", "很有"],
    ["revolution", "变革"],
    ["equality", "平等(n)"],
    ["death", "死亡"],
    ["George Floyd", "乔治·弗洛伊德"],
    ["horrendous", "可怕的"],
    ["dealing with", "处理/处理"],
    ["vigorous lessons", "有力的教训"],
    ["by the door", "在门边"],
    ["quality", "素质/品质"],
    ["deliver", "发布"], 
    ["partnerships", "伙伴关系"],
    ["reward—material", "奖励材料"],
    ["realize", "实现"],
    ["Keep in mind", "记住"],
    ["refresher", "复习"],
    ["course", "课程"],
    ["brave", "勇敢的"],
    ["worry about", "担忧"],
    ["accomplished", "完成了"],
    ["justice", "公正"],
    ["floodlight", "泛光灯"],
    ["clue", "线索"],
    ["unexpected", "出乎意料的"],
    ["insight", "了解/领悟(n)"],
    ["certainly", "毫无疑问的(adv)"],
    ["fault", "过错"],
    ["particularly", "尤其(adv)"],
    ["In other words", "换句话说"],
    ["accurately", "准确的(adv)"],
    ["probably", "很可能"],
    ["pressure", "压力"],
    ["culmination", "顶点/高潮"],
    ["deal with", "处理"],
    ["puzzle", "令人疑惑的/费解的"],
    ["eureka", "[eureka](因找到某物，尤指问题的答案而高兴)我发现了，我找到了"]
    // ["in pairs", "成对"]
];